In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [6]:
np.__version__

'2.3.5'

In [5]:
arr=np.array(2)
arr

array(2)

In [7]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [8]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [9]:
type(my_list
     )

list

In [11]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
np.arange()

TypeError: arange() requires stop to be specified.

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
np.arange(10,20,3,2)

TypeError: Cannot interpret '2' as a data type

In [19]:
np.arange(20,8)

array([], dtype=int64)

In [ ]:
np.arange(-20,-10)              # 1st arg smaller than 2nd

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
np.zeros(10, dtype=complex)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [26]:
np.zeros(10, dtype=bool)

array([False, False, False, False, False, False, False, False, False,
       False])

In [27]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
np.zeros((0,2))

array([], shape=(0, 2), dtype=float64)

In [32]:
np.zeros((2,0))

array([], shape=(2, 0), dtype=float64)

In [36]:
n = np.zeros((5,6))
n

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
len(n)

5

In [39]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
nd1=np.ones((10,10), dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [43]:
y= list(range(2,10))
y

[2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
rand(3,2)

NameError: name 'rand' is not defined

In [45]:
random.rand(2,3)

NameError: name 'random' is not defined

In [46]:
np.random.rand(2,3)

array([[0.56018918, 0.66342657, 0.41875078],
       [0.41605335, 0.84180329, 0.2995939 ]])

In [47]:
np.random.rand(2)

array([0.77671319, 0.40714546])

In [49]:
np.random.rand(2,3)

array([[0.1996061 , 0.65689955, 0.85062987],
       [0.28859875, 0.58673463, 0.20479968]])

In [53]:
np.random.randint(2)

1

In [54]:
np.random.randint(5,20)

14

In [56]:
np.random.randint(2,10,4)

array([5, 3, 9, 7], dtype=int32)

In [57]:
np.random.randint(-30,9,4)

array([ -6, -18,  -3, -11], dtype=int32)

In [58]:
np.random.randint(0,10,(10,10))

array([[2, 6, 8, 4, 1, 6, 7, 0, 6, 2],
       [2, 0, 9, 7, 7, 9, 5, 4, 0, 1],
       [7, 6, 9, 6, 0, 0, 8, 3, 7, 8],
       [7, 1, 0, 8, 8, 2, 8, 5, 9, 7],
       [0, 8, 3, 0, 5, 0, 9, 5, 9, 8],
       [2, 8, 2, 9, 1, 3, 1, 7, 9, 1],
       [2, 1, 5, 2, 2, 3, 7, 5, 5, 1],
       [5, 1, 7, 0, 7, 0, 0, 6, 1, 9],
       [4, 2, 2, 3, 9, 2, 7, 2, 7, 6],
       [3, 0, 4, 4, 1, 8, 9, 0, 1, 3]], dtype=int32)

In [61]:
m=np.random.randint(0,40,(10,10))
m

array([[38,  1, 24, 38, 21,  6, 37, 13,  6,  1],
       [21, 22, 24, 36, 33, 39,  3, 20, 29,  7],
       [22, 33, 24,  2, 27, 13, 39,  0, 17,  9],
       [13,  4,  0, 21, 26, 12, 33, 34, 16, 38],
       [15, 31, 23,  8, 15, 20,  8, 35, 21, 27],
       [23,  7, 16, 32,  0, 13, 34,  5,  2, 32],
       [22, 37, 13, 17,  0, 14, 12,  2,  8, 13],
       [29, 13, 36,  6,  2, 12, 35, 20, 36,  6],
       [ 6, 39, 27, 26, 39, 16, 13, 34,  7, 34],
       [31,  0,  2, 29, 18, 26, 25,  0, 32, 23]], dtype=int32)

In [62]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [65]:
m

array([[38,  1, 24, 38, 21,  6, 37, 13,  6,  1],
       [21, 22, 24, 36, 33, 39,  3, 20, 29,  7],
       [22, 33, 24,  2, 27, 13, 39,  0, 17,  9],
       [13,  4,  0, 21, 26, 12, 33, 34, 16, 38],
       [15, 31, 23,  8, 15, 20,  8, 35, 21, 27],
       [23,  7, 16, 32,  0, 13, 34,  5,  2, 32],
       [22, 37, 13, 17,  0, 14, 12,  2,  8, 13],
       [29, 13, 36,  6,  2, 12, 35, 20, 36,  6],
       [ 6, 39, 27, 26, 39, 16, 13, 34,  7, 34],
       [31,  0,  2, 29, 18, 26, 25,  0, 32, 23]], dtype=int32)

In [67]:
b=np.random.randint(10,20,(5,4))
b

array([[18, 19, 16, 14],
       [12, 15, 14, 18],
       [16, 18, 13, 13],
       [18, 13, 16, 17],
       [13, 17, 11, 10]], dtype=int32)

In [68]:
b[:]

array([[18, 19, 16, 14],
       [12, 15, 14, 18],
       [16, 18, 13, 13],
       [18, 13, 16, 17],
       [13, 17, 11, 10]], dtype=int32)

In [69]:
b[1:4]

array([[12, 15, 14, 18],
       [16, 18, 13, 13],
       [18, 13, 16, 17]], dtype=int32)

In [71]:
b[-1:]

array([[13, 17, 11, 10]], dtype=int32)

In [72]:
b[:-1]

array([[18, 19, 16, 14],
       [12, 15, 14, 18],
       [16, 18, 13, 13],
       [18, 13, 16, 17]], dtype=int32)

In [73]:
b

array([[18, 19, 16, 14],
       [12, 15, 14, 18],
       [16, 18, 13, 13],
       [18, 13, 16, 17],
       [13, 17, 11, 10]], dtype=int32)

In [75]:
b[:-5]

array([], shape=(0, 4), dtype=int32)

In [76]:
b[:-2]

array([[18, 19, 16, 14],
       [12, 15, 14, 18],
       [16, 18, 13, 13]], dtype=int32)

In [77]:
b

array([[18, 19, 16, 14],
       [12, 15, 14, 18],
       [16, 18, 13, 13],
       [18, 13, 16, 17],
       [13, 17, 11, 10]], dtype=int32)

In [80]:
b[0,0]

np.int32(18)

In [81]:
b[1,-1]

np.int32(18)

In [82]:
b[2,0]

np.int32(16)

In [83]:
b

array([[18, 19, 16, 14],
       [12, 15, 14, 18],
       [16, 18, 13, 13],
       [18, 13, 16, 17],
       [13, 17, 11, 10]], dtype=int32)

# numpy operations

In [84]:
arr

array([0, 1, 2, 3, 4, 5])

In [85]:
arr.max()

np.int64(5)

In [86]:
arr.min()

np.int64(0)

In [87]:
arr.mean()

np.float64(2.5)

In [89]:
m=np.random.randint(10,100,(10,10))
m

array([[34, 24, 69, 33, 70, 45, 96, 40, 86, 72],
       [64, 32, 86, 99, 42, 30, 19, 87, 83, 69],
       [17, 23, 69, 79, 57, 96, 40, 84, 15, 54],
       [64, 60, 10, 76, 41, 39, 47, 71, 63, 53],
       [77, 67, 78, 11, 29, 92, 42, 99, 58, 21],
       [77, 68, 20, 90, 27, 78, 60, 84, 44, 60],
       [78, 93, 23, 33, 79, 75, 43, 85, 24, 43],
       [61, 86, 19, 77, 56, 20, 33, 77, 30, 85],
       [22, 25, 60, 92, 94, 73, 78, 58, 50, 31],
       [76, 65, 20, 44, 99, 43, 82, 43, 28, 38]], dtype=int32)

In [90]:
row=4
col=5

In [91]:
m[row,col]

np.int32(92)

In [92]:
row=6
col=9

In [93]:
m[row,col]

np.int32(43)

In [94]:
m[1]

array([64, 32, 86, 99, 42, 30, 19, 87, 83, 69], dtype=int32)

In [96]:
m

array([[34, 24, 69, 33, 70, 45, 96, 40, 86, 72],
       [64, 32, 86, 99, 42, 30, 19, 87, 83, 69],
       [17, 23, 69, 79, 57, 96, 40, 84, 15, 54],
       [64, 60, 10, 76, 41, 39, 47, 71, 63, 53],
       [77, 67, 78, 11, 29, 92, 42, 99, 58, 21],
       [77, 68, 20, 90, 27, 78, 60, 84, 44, 60],
       [78, 93, 23, 33, 79, 75, 43, 85, 24, 43],
       [61, 86, 19, 77, 56, 20, 33, 77, 30, 85],
       [22, 25, 60, 92, 94, 73, 78, 58, 50, 31],
       [76, 65, 20, 44, 99, 43, 82, 43, 28, 38]], dtype=int32)

In [95]:
m[:,0]

array([34, 64, 17, 64, 77, 77, 78, 61, 22, 76], dtype=int32)

In [97]:
m[::-1]

array([[76, 65, 20, 44, 99, 43, 82, 43, 28, 38],
       [22, 25, 60, 92, 94, 73, 78, 58, 50, 31],
       [61, 86, 19, 77, 56, 20, 33, 77, 30, 85],
       [78, 93, 23, 33, 79, 75, 43, 85, 24, 43],
       [77, 68, 20, 90, 27, 78, 60, 84, 44, 60],
       [77, 67, 78, 11, 29, 92, 42, 99, 58, 21],
       [64, 60, 10, 76, 41, 39, 47, 71, 63, 53],
       [17, 23, 69, 79, 57, 96, 40, 84, 15, 54],
       [64, 32, 86, 99, 42, 30, 19, 87, 83, 69],
       [34, 24, 69, 33, 70, 45, 96, 40, 86, 72]], dtype=int32)

In [98]:
m[::-2]

array([[76, 65, 20, 44, 99, 43, 82, 43, 28, 38],
       [61, 86, 19, 77, 56, 20, 33, 77, 30, 85],
       [77, 68, 20, 90, 27, 78, 60, 84, 44, 60],
       [64, 60, 10, 76, 41, 39, 47, 71, 63, 53],
       [64, 32, 86, 99, 42, 30, 19, 87, 83, 69]], dtype=int32)

In [99]:
m[2:6,2:4]

array([[69, 79],
       [10, 76],
       [78, 11],
       [20, 90]], dtype=int32)

In [100]:
m[0:2,4:9]

array([[70, 45, 96, 40, 86],
       [42, 30, 19, 87, 83]], dtype=int32)

In [101]:
m>50

array([[False, False,  True, False,  True, False,  True, False,  True,
         True],
       [ True, False,  True,  True, False, False, False,  True,  True,
         True],
       [False, False,  True,  True,  True,  True, False,  True, False,
         True],
       [ True,  True, False,  True, False, False, False,  True,  True,
         True],
       [ True,  True,  True, False, False,  True, False,  True,  True,
        False],
       [ True,  True, False,  True, False,  True,  True,  True, False,
         True],
       [ True,  True, False, False,  True,  True, False,  True, False,
        False],
       [ True,  True, False,  True,  True, False, False,  True, False,
         True],
       [False, False,  True,  True,  True,  True,  True,  True, False,
        False],
       [ True,  True, False, False,  True, False,  True, False, False,
        False]])

In [102]:
m[m>50]

array([69, 70, 96, 86, 72, 64, 86, 99, 87, 83, 69, 69, 79, 57, 96, 84, 54,
       64, 60, 76, 71, 63, 53, 77, 67, 78, 92, 99, 58, 77, 68, 90, 78, 60,
       84, 60, 78, 93, 79, 75, 85, 61, 86, 77, 56, 77, 85, 60, 92, 94, 73,
       78, 58, 76, 65, 99, 82], dtype=int32)

In [103]:
m[m<50]

array([34, 24, 33, 45, 40, 32, 42, 30, 19, 17, 23, 40, 15, 10, 41, 39, 47,
       11, 29, 42, 21, 20, 27, 44, 23, 33, 43, 24, 43, 19, 20, 33, 30, 22,
       25, 31, 20, 44, 43, 43, 28, 38], dtype=int32)

In [104]:
m[m!=50]

array([34, 24, 69, 33, 70, 45, 96, 40, 86, 72, 64, 32, 86, 99, 42, 30, 19,
       87, 83, 69, 17, 23, 69, 79, 57, 96, 40, 84, 15, 54, 64, 60, 10, 76,
       41, 39, 47, 71, 63, 53, 77, 67, 78, 11, 29, 92, 42, 99, 58, 21, 77,
       68, 20, 90, 27, 78, 60, 84, 44, 60, 78, 93, 23, 33, 79, 75, 43, 85,
       24, 43, 61, 86, 19, 77, 56, 20, 33, 77, 30, 85, 22, 25, 60, 92, 94,
       73, 78, 58, 31, 76, 65, 20, 44, 99, 43, 82, 43, 28, 38],
      dtype=int32)

In [105]:
m[m==50]

array([50], dtype=int32)

In [108]:
import random 

def generate_otp(length=4):
    digits='0123456789'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp



otp_length = 4
otp = generate_otp(otp_length)
print(f"your otp is: {otp}")

your otp is: 4344
